name: Canopy
main: org.sandcast.canopy.CanopyPlugin
description: Grow custom trees!
version: 0.1
softdepend:
 - WorldEdit
author: Duke_Arioch
website: http://github.com/
api-version: 1.12.2
commands:
  canopy:
    description: Main command of CanopyPlugin.
    aliases:
     - canopy
    usage: /canopy
    permission: canopy.command
permissions:
  owngarden.command:
    default: op
    description: Allows you to use /canopy.
